In [37]:
import utils.get_token as tk
import utils.get_league_data as liga

In [41]:
acesso = tk.get_battle_net_access_token(client_id='14fd2a97eefe4115a3aa2e64e437b6bb',client_secret='JzzXOrIV7pt5vn1iEZ5Iidw6AgvCTyst')

In [42]:
abc = liga.league_data(season_id=65,queue_id=201,team_type=0,league_id=4,token=acesso)

In [1]:
from utils.get_token import get_battle_net_access_token
from utils.get_league_data import league_data


acesso = get_battle_net_access_token(client_id='14fd2a97eefe4115a3aa2e64e437b6bb',client_secret='JzzXOrIV7pt5vn1iEZ5Iidw6AgvCTyst')
abc = league_data(season_id=65,queue_id=201,team_type=0,league_id=4,token=acesso)

print(abc)

    id  ladder_id  member_count  tier_index  tier_min_rating  tier_max_rating  \
0   39     332622           100           0             3867             4240
1   60     332818           100           0             3867             4240
2   47     332700           100           0             3867             4240
3   25     332507           100           0             3867             4240
4   32     332564           100           0             3867             4240
..  ..        ...           ...         ...              ...              ...
95  91     333125           100           2             3120             3493
96  93     333151           100           2             3120             3493
97  96     333166            99           2             3120             3493
98  97     333180            99           2             3120             3493
99  99     333207           100           2             3120             3493

    season_id  queue_id  league_id
0          65       201          4
1          65       201          4
2          65       201          4
3          65       201          4
4          65       201          4
..        ...       ...        ...
95         65       201          4
96         65       201          4
97         65       201          4
98         65       201          4
99         65       201          4

[100 rows x 9 columns]

In [2]:
abc

,id,ladder_id,member_count,tier_index,tier_min_rating,tier_max_rating,season_id,queue_id,league_id
0,39,332622,100,0,3867,4240,65,201,4
1,60,332818,100,0,3867,4240,65,201,4
2,47,332700,100,0,3867,4240,65,201,4
3,25,332507,100,0,3867,4240,65,201,4
4,32,332564,100,0,3867,4240,65,201,4
...,...,...,...,...,...,...,...,...,...
95,91,333125,100,2,3120,3493,65,201,4
96,93,333151,100,2,3120,3493,65,201,4
97,96,333166,99,2,3120,3493,65,201,4
98,97,333180,99,2,3120,3493,65,201,4
99,99,333207,100,2,3120,3493,65,201,4

In [31]:
import pandas as pd

#pd.json_normalize(teste['tier'][0]['division'])

4240

In [35]:
# Criar uma única estrutura de dados com todos os tiers e divisões
all_data = []

for i, tier in enumerate(data['tier']):
    # Normalizar as divisões do tier atual
    df_divisions = pd.json_normalize(tier['division'])
    
    # Adicionar informações do tier às divisões
    df_divisions['tier_index'] = i
    df_divisions['tier_min_rating'] = tier['min_rating']
    df_divisions['tier_max_rating'] = tier['max_rating']
    
    # Adicionar à lista
    all_data.append(df_divisions)

# Concatenar todos os DataFrames em um só
df_completo = pd.concat(all_data, ignore_index=True)

# Adicionar informações globais da chave (temporada, liga, etc)
df_completo['season_id'] = teste['key']['season_id']
df_completo['queue_id'] = teste['key']['queue_id']
df_completo['league_id'] = teste['key']['league_id']

# Armazenar o resultado na variável para uso posterior
dados_estruturados = df_completo

In [36]:
df_completo

,id,ladder_id,member_count,tier_index,tier_min_rating,tier_max_rating,season_id,queue_id,league_id
0,39,332622,100,0,3867,4240,65,201,4
1,60,332818,100,0,3867,4240,65,201,4
2,47,332700,100,0,3867,4240,65,201,4
3,25,332507,100,0,3867,4240,65,201,4
4,32,332564,100,0,3867,4240,65,201,4
...,...,...,...,...,...,...,...,...,...
95,91,333125,100,2,3120,3493,65,201,4
96,93,333151,100,2,3120,3493,65,201,4
97,96,333166,99,2,3120,3493,65,201,4
98,97,333180,99,2,3120,3493,65,201,4
99,99,333207,100,2,3120,3493,65,201,4

{'id': 2,
 'min_rating': 3120,
 'max_rating': 3493,
 'division': [{'id': 69, 'ladder_id': 332908, 'member_count': 100},
  {'id': 22, 'ladder_id': 332491, 'member_count': 100},
  {'id': 1, 'ladder_id': 332246, 'member_count': 99},
  {'id': 82, 'ladder_id': 333035, 'member_count': 99},
  {'id': 30, 'ladder_id': 332556, 'member_count': 100},
  {'id': 90, 'ladder_id': 333113, 'member_count': 99},
  {'id': 85, 'ladder_id': 333058, 'member_count': 100},
  {'id': 68, 'ladder_id': 332892, 'member_count': 100},
  {'id': 38, 'ladder_id': 332614, 'member_count': 100},
  {'id': 17, 'ladder_id': 332445, 'member_count': 100},
  {'id': 76, 'ladder_id': 332981, 'member_count': 100},
  {'id': 46, 'ladder_id': 332686, 'member_count': 100},
  {'id': 8, 'ladder_id': 332360, 'member_count': 99},
  {'id': 71, 'ladder_id': 332935, 'member_count': 100},
  {'id': 54, 'ladder_id': 332754, 'member_count': 100},
  {'id': 33, 'ladder_id': 332577, 'member_count': 100},
  {'id': 79, 'ladder_id': 333019, 'member_count': 100},
  {'id': 62, 'ladder_id': 332842, 'member_count': 100},
  {'id': 24, 'ladder_id': 332502, 'member_count': 99},
  {'id': 11, 'ladder_id': 332384, 'member_count': 100},
  {'id': 87, 'ladder_id': 333071, 'member_count': 100},
  {'id': 19, 'ladder_id': 332469, 'member_count': 99},
  {'id': 78, 'ladder_id': 332999, 'member_count': 100},
  {'id': 57, 'ladder_id': 332799, 'member_count': 100},
  {'id': 40, 'ladder_id': 332627, 'member_count': 100},
  {'id': 27, 'ladder_id': 332527, 'member_count': 100},
  {'id': 10, 'ladder_id': 332371, 'member_count': 99},
  {'id': 65, 'ladder_id': 332871, 'member_count': 99},
  {'id': 48, 'ladder_id': 332706, 'member_count': 99},
  {'id': 35, 'ladder_id': 332591, 'member_count': 99},
  {'id': 13, 'ladder_id': 332401, 'member_count': 100},
  {'id': 73, 'ladder_id': 332947, 'member_count': 100},
  {'id': 56, 'ladder_id': 332783, 'member_count': 99},
  {'id': 43, 'ladder_id': 332654, 'member_count': 100},
  {'id': 26, 'ladder_id': 332512, 'member_count': 99},
  {'id': 4, 'ladder_id': 332331, 'member_count': 99},
  {'id': 64, 'ladder_id': 332855, 'member_count': 99},
  {'id': 51, 'ladder_id': 332738, 'member_count': 99},
  {'id': 29, 'ladder_id': 332539, 'member_count': 99},
  {'id': 89, 'ladder_id': 333092, 'member_count': 99},
  {'id': 42, 'ladder_id': 332640, 'member_count': 99},
  {'id': 20, 'ladder_id': 332484, 'member_count': 100},
  {'id': 50, 'ladder_id': 332721, 'member_count': 100},
  {'id': 15, 'ladder_id': 332423, 'member_count': 99},
  {'id': 75, 'ladder_id': 332960, 'member_count': 100},
  {'id': 58, 'ladder_id': 332809, 'member_count': 100},
  {'id': 36, 'ladder_id': 332603, 'member_count': 100},
  {'id': 6, 'ladder_id': 332346, 'member_count': 99},
  {'id': 83, 'ladder_id': 333042, 'member_count': 100},
  {'id': 61, 'ladder_id': 332829, 'member_count': 99},
  {'id': 44, 'ladder_id': 332667, 'member_count': 99},
  {'id': 91, 'ladder_id': 333125, 'member_count': 100},
  {'id': 93, 'ladder_id': 333151, 'member_count': 100},
  {'id': 96, 'ladder_id': 333166, 'member_count': 99},
  {'id': 97, 'ladder_id': 333180, 'member_count': 99},
  {'id': 99, 'ladder_id': 333207, 'member_count': 100}]}

In [8]:
teste

{'_links': {'self': {'href': 'https://us.api.blizzard.com/data/sc2/league/65/201/0/4?namespace=prod'}},
 'key': {'league_id': 4, 'season_id': 65, 'queue_id': 201, 'team_type': 0},
 'tier': [{'id': 0,
   'min_rating': 3867,
   'max_rating': 4240,
   'division': [{'id': 39, 'ladder_id': 332622, 'member_count': 100},
    {'id': 60, 'ladder_id': 332818, 'member_count': 100},
    {'id': 47, 'ladder_id': 332700, 'member_count': 100},
    {'id': 25, 'ladder_id': 332507, 'member_count': 100},
    {'id': 32, 'ladder_id': 332564, 'member_count': 100},
    {'id': 2, 'ladder_id': 332250, 'member_count': 100},
    {'id': 86, 'ladder_id': 333070, 'member_count': 100},
    {'id': 18, 'ladder_id': 332461, 'member_count': 100},
    {'id': 81, 'ladder_id': 333025, 'member_count': 100},
    {'id': 72, 'ladder_id': 332942, 'member_count': 100},
    {'id': 7, 'ladder_id': 332359, 'member_count': 100},
    {'id': 67, 'ladder_id': 332888, 'member_count': 100},
    {'id': 53, 'ladder_id': 332751, 'member_count': 100},
    {'id': 14, 'ladder_id': 332404, 'member_count': 100},
    {'id': 94, 'ladder_id': 333153, 'member_count': 99},
    {'id': 100, 'ladder_id': 333223, 'member_count': 4}]},
  {'id': 1,
   'min_rating': 3493,
   'max_rating': 3867,
   'division': [{'id': 52, 'ladder_id': 332746, 'member_count': 100},
    {'id': 77, 'ladder_id': 332986, 'member_count': 100},
    {'id': 9, 'ladder_id': 332366, 'member_count': 96},
    {'id': 55, 'ladder_id': 332779, 'member_count': 98},
    {'id': 63, 'ladder_id': 332854, 'member_count': 99},
    {'id': 84, 'ladder_id': 333052, 'member_count': 97},
    {'id': 16, 'ladder_id': 332442, 'member_count': 99},
    {'id': 3, 'ladder_id': 332255, 'member_count': 99},
    {'id': 92, 'ladder_id': 333129, 'member_count': 97},
    {'id': 41, 'ladder_id': 332631, 'member_count': 99},
    {'id': 70, 'ladder_id': 332923, 'member_count': 100},
    {'id': 49, 'ladder_id': 332711, 'member_count': 99},
    {'id': 5, 'ladder_id': 332343, 'member_count': 99},
    {'id': 21, 'ladder_id': 332485, 'member_count': 97},
    {'id': 34, 'ladder_id': 332590, 'member_count': 99},
    {'id': 12, 'ladder_id': 332399, 'member_count': 99},
    {'id': 59, 'ladder_id': 332810, 'member_count': 99},
    {'id': 37, 'ladder_id': 332611, 'member_count': 99},
    {'id': 80, 'ladder_id': 333024, 'member_count': 99},
    {'id': 45, 'ladder_id': 332675, 'member_count': 100},
    {'id': 28, 'ladder_id': 332530, 'member_count': 98},
    {'id': 88, 'ladder_id': 333085, 'member_count': 99},
    {'id': 23, 'ladder_id': 332501, 'member_count': 100},
    {'id': 66, 'ladder_id': 332886, 'member_count': 100},
    {'id': 31, 'ladder_id': 332562, 'member_count': 99},
    {'id': 74, 'ladder_id': 332955, 'member_count': 100},
    {'id': 95, 'ladder_id': 333162, 'member_count': 95},
    {'id': 98, 'ladder_id': 333203, 'member_count': 83}]},
  {'id': 2,
   'min_rating': 3120,
   'max_rating': 3493,
   'division': [{'id': 69, 'ladder_id': 332908, 'member_count': 100},
    {'id': 22, 'ladder_id': 332491, 'member_count': 100},
    {'id': 1, 'ladder_id': 332246, 'member_count': 99},
    {'id': 82, 'ladder_id': 333035, 'member_count': 99},
    {'id': 30, 'ladder_id': 332556, 'member_count': 100},
    {'id': 90, 'ladder_id': 333113, 'member_count': 99},
    {'id': 85, 'ladder_id': 333058, 'member_count': 100},
    {'id': 68, 'ladder_id': 332892, 'member_count': 100},
    {'id': 38, 'ladder_id': 332614, 'member_count': 100},
    {'id': 17, 'ladder_id': 332445, 'member_count': 100},
    {'id': 76, 'ladder_id': 332981, 'member_count': 100},
    {'id': 46, 'ladder_id': 332686, 'member_count': 100},
    {'id': 8, 'ladder_id': 332360, 'member_count': 99},
    {'id': 71, 'ladder_id': 332935, 'member_count': 100},
    {'id': 54, 'ladder_id': 332754, 'member_count': 100},
    {'id': 33, 'ladder_id': 332577, 'member_count': 100},
    {'id': 79, 'ladder_id': 333019, 'member_count': 100},
    {'id': 62, 'ladder_id': 332842, 'member_count': 100},
    {'id': 24, 'ladder_id': 332502, 'member_count': 99},
    {'id': 11, 'ladder_id': 332384, 'member_count': 100},
    {'id': 87, 'ladder_id': 333071, 'member_count': 100},
    {'id': 19, 'ladder_id': 332469, 'member_count': 99},
    {'id': 78, 'ladder_id': 332999, 'member_count': 100},
    {'id': 57, 'ladder_id': 332799, 'member_count': 100},
    {'id': 40, 'ladder_id': 332627, 'member_count': 100},
    {'id': 27, 'ladder_id': 332527, 'member_count': 100},
    {'id': 10, 'ladder_id': 332371, 'member_count': 99},
    {'id': 65, 'ladder_id': 332871, 'member_count': 99},
    {'id': 48, 'ladder_id': 332706, 'member_count': 99},
    {'id': 35, 'ladder_id': 332591, 'member_count': 99},
    {'id': 13, 'ladder_id': 332401, 'member_count': 100},
    {'id': 73, 'ladder_id': 332947, 'member_count': 100},
    {'id': 56, 'ladder_id': 332783, 'member_count': 99},
    {'id': 43, 'ladder_id': 332654, 'member_count': 100},
    {'id': 26, 'ladder_id': 332512, 'member_count': 99},
    {'id': 4, 'ladder_id': 332331, 'member_count': 99},
    {'id': 64, 'ladder_id': 332855, 'member_count': 99},
    {'id': 51, 'ladder_id': 332738, 'member_count': 99},
    {'id': 29, 'ladder_id': 332539, 'member_count': 99},
    {'id': 89, 'ladder_id': 333092, 'member_count': 99},
    {'id': 42, 'ladder_id': 332640, 'member_count': 99},
    {'id': 20, 'ladder_id': 332484, 'member_count': 100},
    {'id': 50, 'ladder_id': 332721, 'member_count': 100},
    {'id': 15, 'ladder_id': 332423, 'member_count': 99},
    {'id': 75, 'ladder_id': 332960, 'member_count': 100},
    {'id': 58, 'ladder_id': 332809, 'member_count': 100},
    {'id': 36, 'ladder_id': 332603, 'member_count': 100},
    {'id': 6, 'ladder_id': 332346, 'member_count': 99},
    {'id': 83, 'ladder_id': 333042, 'member_count': 100},
    {'id': 61, 'ladder_id': 332829, 'member_count': 99},
    {'id': 44, 'ladder_id': 332667, 'member_count': 99},
    {'id': 91, 'ladder_id': 333125, 'member_count': 100},
    {'id': 93, 'ladder_id': 333151, 'member_count': 100},
    {'id': 96, 'ladder_id': 333166, 'member_count': 99},
    {'id': 97, 'ladder_id': 333180, 'member_count': 99},
    {'id': 99, 'ladder_id': 333207, 'member_count': 100}]}]}

In [ ]:
import pandas as pd

df = pd.json_normalize(
    data['tier'], 
    record_path=['division'], 
    meta=['id', 'min_rating', 'max_rating'],
    record_prefix='division_',
    meta_prefix='tier_'
)

# 2. Adicionar as informações globais da 'key' (temporada, liga, etc)
df['season_id'] = data['key']['season_id']
df['queue_id'] = data['key']['queue_id']
df['league_id'] = data['key']['league_id']

# Exibir o resultado
print(df.head())

# Opcional: Salvar em CSV para análise posterior
# df.to_csv("sc2_league_structure.csv", index=False)